<?php

namespace App\Console\Commands;

use App\Enums\BuildOptions;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GenerateBuildOptions extends Command
{
    protected $signature = 'generate:build-options {--output=resources/js/build}';

    protected $description = 'Generate TypeScript file with build options from backend enum';

    public function handle(): int
    {
        $outputPath = base_path($this->option('output'));
        $filePath = $outputPath.'/index.ts';

        if (! File::isDirectory($outputPath)) {
            File::makeDirectory($outputPath, 0755, true);
        }

        $options = BuildOptions::all();

        $content = <<<TYPESCRIPT
// AUTO-GENERATED by artisan generate:build-options
// Do not edit manually - changes will be overwritten

export const availableServices = {$this->arrayToTs($options['availableServices'])} as const;
export const availableStarterKits = {$this->arrayToTs($options['availableStarterKits'])} as const;
export const availableJavascriptRuntimes = {$this->arrayToTs($options['availableJavascriptRuntimes'])} as const;
export const availableAuthProviders = {$this->arrayToTs($options['availableAuthProviders'])} as const;
export const availableTestingFrameworks = {$this->arrayToTs($options['availableTestingFrameworks'])} as const;
export const availablePhpVersions = {$this->arrayToTs($options['availablePhpVersions'])} as const;
export const availableDatabaseDrivers = {$this->arrayToTs($options['availableDatabaseDrivers'])} as const;
export const availablePackageFeatures = {$this->arrayToTs($options['availablePackageFeatures'])} as const;

export type AvailableService = typeof availableServices[number];
export type AvailableStarterKit = typeof availableStarterKits[number];
export type AvailableJavascriptRuntime = typeof availableJavascriptRuntimes[number];
export type AvailableAuthProvider = typeof availableAuthProviders[number];
export type AvailableTestingFramework = typeof availableTestingFrameworks[number];
export type AvailablePhpVersion = typeof availablePhpVersions[number];
export type AvailableDatabaseDriver = typeof availableDatabaseDrivers[number];
export type AvailablePackageFeature = typeof availablePackageFeatures[number];
TYPESCRIPT;

        File::put($filePath, $content);

        $this->info("Generated: {$filePath}");

        return Command::SUCCESS;
    }

    /**
     * @param  array<string>  $array
     */
    private function arrayToTs(array $array): string
    {
        $items = array_map(fn (string $item) => "'{$item}'", $array);

        return '['.\implode(', ', $items).']';
    }
}
